# Generated by Django 3.0.10 on 2020-09-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinicmaintenance",
            fields=[
                (
                    "clinic_id",
                    models.AutoField(
                        db_column="ClinicId", primary_key=True, serialize=False
                    ),
                ),
                ("clinic_name", models.TextField(db_column="ClinicName")),
                ("clinic_address", models.TextField(db_column="ClinicAddress")),
                (
                    "landing_pageurl",
                    models.TextField(blank=True, db_column="LandingPageUrl", null=True),
                ),
                ("created_by", models.CharField(db_column="CreatedBy", max_length=100)),
                ("created_date", models.DateTimeField(db_column="CreatedDate")),
                (
                    "modified_by",
                    models.CharField(db_column="ModifiedBy", max_length=100),
                ),
                ("modified_date", models.DateTimeField(db_column="ModifiedDate")),
                (
                    "shoppingurl",
                    models.TextField(blank=True, db_column="ShoppingUrl", null=True),
                ),
                ("latitude", models.CharField(db_column="Latitude", max_length=100)),
                ("longitude", models.CharField(db_column="Longitude", max_length=100)),
            ],
            options={
                "db_table": "ClinicMaintenance",
            },
        ),
        migrations.CreateModel(
            name="Venuesocialmediaapplications",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("application_name", models.TextField(db_column="ApplicationName")),
                ("is_active", models.BooleanField(db_column="IsActive")),
                (
                    "is_socialmedia_app",
                    models.BooleanField(db_column="IsSocialMediaApp"),
                ),
                ("created_by", models.CharField(db_column="CreatedBy", max_length=100)),
                ("created_date", models.DateTimeField(db_column="CreatedDate")),
                (
                    "modified_by",
                    models.CharField(db_column="ModifiedBy", max_length=100),
                ),
                ("modified_date", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "VenueSocialMediaApplications",
            },
        ),
        migrations.CreateModel(
            name="Ssids",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("mac_address", models.TextField(db_column="Macaddress")),
                ("ssid", models.TextField(db_column="Ssid")),
                ("lan_ip", models.TextField(db_column="Lanip")),
                ("public_ip", models.TextField(db_column="Publicip")),
                ("model", models.TextField(db_column="Model")),
                ("serial_number", models.TextField(db_column="SerialNumber")),
                ("created_by", models.CharField(db_column="CreatedBy", max_length=100)),
                ("created_date", models.DateTimeField(db_column="CreatedDate")),
                (
                    "modified_by",
                    models.CharField(db_column="ModifiedBy", max_length=100),
                ),
                ("modified_date", models.DateTimeField(db_column="ModifiedDate")),
                (
                    "clinic_id",
                    models.ForeignKey(
                        db_column="ClinicId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="emailscraper.Clinicmaintenance",
                    ),
                ),
            ],
            options={
                "db_table": "Ssids",
            },
        ),
        migrations.CreateModel(
            name="Networkusagestatistics",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "total_data_transferred",
                    models.FloatField(db_column="TotalDataTransferred"),
                ),
                (
                    "total_data_downloaded",
                    models.FloatField(db_column="TotalDataDownloaded"),
                ),
                (
                    "total_data_uploaded",
                    models.FloatField(db_column="TotalDataUploaded"),
                ),
                ("data_unit", models.TextField(db_column="DataUnit")),
                ("email_date", models.DateTimeField(db_column="EmailDate")),
                ("created_by", models.CharField(db_column="CreatedBy", max_length=100)),
                ("created_date", models.DateTimeField(db_column="CreatedDate")),
                (
                    "modified_by",
                    models.CharField(db_column="ModifiedBy", max_length=100),
                ),
                ("modified_date", models.DateTimeField(db_column="ModifiedDate")),
                (
                    "ssid_mac_address",
                    models.CharField(db_column="SsidMacAddress", max_length=450),
                ),
                (
                    "clinic_id",
                    models.ForeignKey(
                        db_column="ClinicId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="emailscraper.Clinicmaintenance",
                    ),
                ),
            ],
            options={
                "db_table": "NetworkUsageStatistics",
            },
        ),
        migrations.CreateModel(
            name="Applicationusagestatistics",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("application_name", models.TextField(db_column="ApplicationName")),
                ("usage", models.FloatField(db_column="Usage")),
                ("data_unit", models.TextField(db_column="DataUnit")),
                ("email_date", models.DateTimeField(db_column="EmailDate")),
                ("created_by", models.CharField(db_column="CreatedBy", max_length=100)),
                ("created_date", models.DateTimeField(db_column="CreatedDate")),
                (
                    "modified_by",
                    models.CharField(db_column="ModifiedBy", max_length=100),
                ),
                ("modified_date", models.DateTimeField(db_column="ModifiedDate")),
                (
                    "ssid_mac_address",
                    models.CharField(db_column="SsidMacAddress", max_length=450),
                ),
                (
                    "clinic_id",
                    models.ForeignKey(
                        db_column="ClinicId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="emailscraper.Clinicmaintenance",
                    ),
                ),
            ],
            options={
                "db_table": "ApplicationUsageStatistics",
            },
        ),
    ]
