# Generated by Django 3.0.10 on 2020-09-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationusagestatistics',
            name='clinic_id',
            field=models.ForeignKey(db_column='ClinicId', on_delete=django.db.models.deletion.DO_NOTHING, to='emailscraper.ClinicMaintenance'),
        ),
        migrations.AlterField(
            model_name='networkusagestatistics',
            name='clinic_id',
            field=models.ForeignKey(db_column='ClinicId', on_delete=django.db.models.deletion.DO_NOTHING, to='emailscraper.ClinicMaintenance'),
        ),
        migrations.AlterField(
            model_name='ssids',
            name='clinic_id',
            field=models.ForeignKey(db_column='ClinicId', on_delete=django.db.models.deletion.DO_NOTHING, to='emailscraper.ClinicMaintenance'),
        ),
    ]
